apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# Optional: a namespace-scoped issuer if you prefer (Rancher uses cattle-system)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rancher-selfsigned
  namespace: cattle-system
spec:
  selfSigned: {}